[project]
name = "pyqttutorial"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "black==25.1.0",
    "mysql-connector-python==8.0.26",
    "pip==25.0.1",
    "pymysql==1.1.1",
    "pyqt6==6.8.1",
    "pyside6>=6.8.2.1",
]
