# Form implementation generated from reading ui file '1.8_WindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets  # 导入PyQt6的相关模块


class Ui_Form(object):  # 定义Ui_Form类，继承自object
    def setupUi(self, Form):  # 定义setupUi方法，用于设置UI界面
        Form.setObjectName("Form")  # 设置窗体对象名称
        Form.resize(400, 300)  # 设置窗体大小
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))

        self.retranslateUi(Form)  # 调用retranslateUi方法，用于翻译UI界面文本

    def retranslateUi(self, Form):  # 定义retranslateUi方法，用于翻译UI界面文本
        _translate = QtCore.QCoreApplication.translate  # 获取翻译函数
        Form.setWindowTitle(_translate("Form", "QT Designer Example"))  # 设置窗体标题


if __name__ == "__main__":  # 如果当前文件作为主程序运行
    import sys  # 导入sys模块

    app = QtWidgets.QApplication(sys.argv)  # 创建QApplication对象
    Form = QtWidgets.QWidget()  # 创建QWidget对象
    ui = Ui_Form()  # 创建Ui_Form对象
    ui.setupUi(Form)  # 调用setupUi方法，设置UI界面
    Form.show()  # 显示窗体
    sys.exit(app.exec())  # 进入应用程序的主循环，并等待退出
