# Form implementation generated from reading ui file '02_15_CheckDemo.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QStyle


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(583, 319)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(20)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(parent=Dialog)

        self.checkBox_1.stateChanged.connect(self.temp)

        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(12)
        font.setBold(True)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName("checkBox_1")
        self.verticalLayout.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Dialog)

        self.checkBox_2.stateChanged.connect(self.temp)

        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(12)
        font.setBold(True)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Dialog)

        self.checkBox_3.stateChanged.connect(self.temp)

        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(12)
        font.setBold(True)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(16)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("现在我有10枚金币")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "我只有10枚金币"))
        self.label_2.setText(_translate("Dialog", "爆点金币："))
        self.checkBox_1.setText(_translate("Dialog", "1：10枚金币"))
        self.checkBox_2.setText(_translate("Dialog", "2：100枚金币"))
        self.checkBox_3.setText(_translate("Dialog", "3：1000枚金币"))

    def temp(self):
        value = 10

        if self.checkBox_1.isChecked():
            value += 10

        if self.checkBox_2.isChecked():
            value += 100

        if self.checkBox_3.isChecked():
            value += 1000

        self.label_result.setText(f"现在我有{value}枚金币")
        self.label_result.setStyleSheet("QLabel {color:red}")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
