# Form implementation generated from reading ui file '02_18_DoubleSpinBoxDemo.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 200)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_gold_price = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_gold_price.setFont(font)
        self.lineEdit_gold_price.setObjectName("lineEdit_gold_price")
        self.horizontalLayout.addWidget(self.lineEdit_gold_price)
        self.spinBox = QtWidgets.QSpinBox(parent=Form)
        self.spinBox.setObjectName("spinBox")

        self.spinBox.editingFinished.connect(self.gold_result)

        self.horizontalLayout.addWidget(self.spinBox)
        self.lineEdit_gold_total = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_gold_total.setFont(font)
        self.lineEdit_gold_total.setObjectName("lineEdit_gold_total")
        self.horizontalLayout.addWidget(self.lineEdit_gold_total)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_silver_price = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_silver_price.setFont(font)
        self.lineEdit_silver_price.setObjectName("lineEdit_silver_price")
        self.horizontalLayout_2.addWidget(self.lineEdit_silver_price)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=Form)
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.doubleSpinBox.editingFinished.connect(self.silver_result)

        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.lineEdit_silver_total = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_silver_total.setFont(font)
        self.lineEdit_silver_total.setObjectName("lineEdit_silver_total")
        self.horizontalLayout_2.addWidget(self.lineEdit_silver_total)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_result = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("等距更纱黑体 SC")
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def gold_result(self):
        try:
            if self.lineEdit_gold_price.text() != 0:
                price = int(self.lineEdit_gold_price.text())
                total = price * self.spinBox.value()
                self.lineEdit_gold_total.setStyleSheet("QLineEdit {color:black}")
                self.lineEdit_gold_total.setText(str(total))
        except Exception:
            self.lineEdit_gold_total.setStyleSheet("QLineEdit {color:red}")
            self.lineEdit_gold_total.setText("输入的值错误！")

    def silver_result(self):
        try:
            if self.lineEdit_silver_price.text() != 0:
                price = float(self.lineEdit_silver_price.text())
                total = price * self.doubleSpinBox.value()
                self.lineEdit_silver_total.setStyleSheet("QLineEdit {color:black}")
                self.lineEdit_silver_total.setText(str(total))

                total_result = float(self.lineEdit_silver_total.text()) + total
                self.label_result.setText(str(total_result))

        except Exception as e:
            print(e)
            self.lineEdit_silver_total.setStyleSheet("QLineEdit {color:red}")
            self.lineEdit_silver_total.setText("输入的值错误！")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "金价："))
        self.label_2.setText(_translate("Form", "银价："))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
