# Form implementation generated from reading ui file '02_13_RadioDemo.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(339, 323)
        Dialog.setStyleSheet("QLabel{color:purple}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_py = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_py.setFont(font)
        self.radioButton_py.setObjectName("radioButton_py")
        self.verticalLayout.addWidget(self.radioButton_py)
        self.radioButton_java = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_java.setFont(font)
        self.radioButton_java.setObjectName("radioButton_java")
        self.verticalLayout.addWidget(self.radioButton_java)
        self.radioButton_js = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_js.setFont(font)
        self.radioButton_js.setObjectName("radioButton_js")
        self.verticalLayout.addWidget(self.radioButton_js)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_deb = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_deb.setFont(font)
        self.radioButton_deb.setObjectName("radioButton_deb")
        self.verticalLayout_2.addWidget(self.radioButton_deb)
        self.radioButton_paypal = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_paypal.setFont(font)
        self.radioButton_paypal.setObjectName("radioButton_paypal")
        self.verticalLayout_2.addWidget(self.radioButton_paypal)
        self.radioButton_cash = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_cash.setFont(font)
        self.radioButton_cash.setObjectName("radioButton_cash")
        self.verticalLayout_2.addWidget(self.radioButton_cash)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_3.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        selected1 = ""
        selected2 = ""

        if self.radioButton_py.isChecked() == True:
            selected1 = "Python"
        if self.radioButton_java.isChecked() == True:
            selected1 = "Java"
        if self.radioButton_js.isChecked() == True:
            selected1 = "JavaScript"

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose Your Books"))
        self.radioButton_py.setText(_translate("Dialog", "Python"))
        self.radioButton_java.setText(_translate("Dialog", "Java"))
        self.radioButton_js.setText(_translate("Dialog", "JavaScript"))
        self.label_2.setText(_translate("Dialog", "Choose Your Payment Method"))
        self.radioButton_deb.setText(_translate("Dialog", "Debit/Credit Card"))
        self.radioButton_paypal.setText(_translate("Dialog", "Paypal"))
        self.radioButton_cash.setText(_translate("Dialog", "Cash"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
