# Form implementation generated from reading ui file '02.12_FlightDemo.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QDialog {background-color: yellow}\n"
                             "QLabel {color:green}\n"
                             ""
                             )
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_first = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_first.setFont(font)
        self.radioButton_first.setObjectName("radioButton_first")

        self.radioButton_first.toggled.connect(self.radio_selected)

        self.verticalLayout.addWidget(self.radioButton_first)
        self.radioButton_busniess = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_busniess.setFont(font)
        self.radioButton_busniess.setObjectName("radioButton_busniess")

        self.radioButton_busniess.toggled.connect(self.radio_selected)

        self.verticalLayout.addWidget(self.radioButton_busniess)
        self.radioButton_economy = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_economy.setFont(font)
        self.radioButton_economy.setObjectName("radioButton_economy")

        self.radioButton_economy.toggled.connect(self.radio_selected)


        self.verticalLayout.addWidget(self.radioButton_economy)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        radio_btn = self.sender()
        if radio_btn.isChecked():
            self.label_result.setText(f"You have selected : {radio_btn.text()}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select flight Type"))
        self.radioButton_first.setText(_translate("Dialog", "First Class    $150"))
        self.radioButton_busniess.setText(_translate("Dialog", "Busniess Class $120"))
        self.radioButton_economy.setText(_translate("Dialog", "Economy Class  $100"))
        self.label_result.setText(_translate("Dialog", ""))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
