# Form implementation generated from reading ui file '2.9_Event.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        # 设置窗口的基本属性
        Form.setObjectName("Form")  # 设置窗口对象名称，方便通过名称查找控件
        Form.resize(400, 250)  # 设置窗口大小为400x250像素

        # 设置窗口字体加粗，使文本更显眼
        font = QtGui.QFont()
        font.setBold(True)
        Form.setFont(font)

        # 创建垂直布局管理器，用于管理窗口内的所有控件
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")  # 设置布局对象名称

        # 第一行：包含按钮和输入框
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        # 按钮“点击我”
        self.btn_click = QtWidgets.QPushButton(parent=Form)
        self.btn_click.setObjectName("btn_click")  # 设置按钮对象名称

        # 绑定按钮点击事件到cilck_me方法
        self.btn_click.clicked.connect(self.cilck_me)

        self.horizontalLayout.addWidget(self.btn_click)  # 将按钮添加到水平布局中

        # 输入框，用于用户输入文本
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setObjectName("lineEdit")  # 设置输入框对象名称
        self.horizontalLayout.addWidget(self.lineEdit)  # 将输入框添加到水平布局中

        # 将第一行添加到垂直布局中
        self.verticalLayout.addLayout(self.horizontalLayout)

        # 结果标签，用于显示输入的文本
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)  # 设置字体大小为16点
        font.setBold(True)  # 设置字体加粗，使结果更显眼
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {color:red}")  # 设置文本颜色为红色
        self.label.setText("")  # 初始化为空字符串
        self.label.setObjectName("label")  # 设置标签对象名称

        self.verticalLayout.addWidget(self.label)  # 将标签添加到垂直布局中

        self.retranslateUi(Form)  # 设置界面文本
        QtCore.QMetaObject.connectSlotsByName(Form)  # 连接信号和槽

    def cilck_me(self):
        # 获取输入框中的文本，并将其设置为标签的文本
        mytext = self.lineEdit.text()  # 获取输入框中的文本
        self.label.setText(mytext)  # 将获取的文本设置为标签的文本

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QT Designer Application"))  # 设置窗口标题
        self.btn_click.setText(_translate("Form", "点击我"))  # 设置按钮文本
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入您的名字"))  # 设置输入框占位符文本


if __name__ == "__main__":
    import sys

    # 创建应用程序实例
    app = QtWidgets.QApplication(sys.argv)

    # 创建主窗口部件
    Form = QtWidgets.QWidget()

    # 创建UI类实例并设置UI布局
    ui = Ui_Form()
    ui.setupUi(Form)

    # 显示窗口
    Form.show()

    # 进入应用程序主循环
    sys.exit(app.exec())
